backend:
  name: git-gateway
  branch: main

media_folder: "uploads/images"
public_folder: "/uploads/images"

collections:
  - name: "articles"
    label: "articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
